# Generated by Django 2.2.16 on 2022-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='y6gsfq#@gz7dp3lgp7%)f52g8dovhr1&w888so3y)#)hir#d2g', max_length=64, verbose_name='Код подтверждения'),
        ),
    ]
