# Generated by Django 2.2.16 on 2022-05-12 14:49

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220512_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Год создания произведения', validators=[reviews.validators.validator_year], verbose_name='Год'),
        ),
    ]
