# Generated by Django 2.2.16 on 2022-05-12 15:21

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220512_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(help_text='Год создания произведения', validators=[reviews.validators.validator_year], verbose_name='Год'),
        ),
    ]
